### ISSUE TITLE
Template lookup for apps within different directories

### ISSUE THREAD

**Issue by axsuul** [emberjs/ember-rails#175]
I have an Ember application within a subdirectory within my `assets` folder within my Rails app. So

```
app
    assets
        javascripts
            booking
                controllers
                helpers
                models
                routes
                templates
```

In order to reference the correct template however, I have to do

``` coffeescript
Booking.ApplicationView = Ember.View.extend
  templateName: 'booking/application'
```

Is there any way to have it know to reference the templates directory within `booking/`? I have tried

``` ruby
config.handlebars.templates_root = 'booking/templates'
```

but the template still seems to be placed in `Ember.TEMPLATES['booking/application']` and **not** `Ember.TEMPLATES['application']`.

**Comment by arthurtalkgoal** [comment]
Hi @sohara,

I have the same issue, I have "wireframe" inside "app/assets/javascripts"

and got the error
```
SyntaxError: missing ] after element list
	
Ember.TEMPLATES["wireframe/panel"] = Ember.Handlebars.template([object Object]);
```
I tried to restart rails a few times, still ruin.

**Comment by tricknotes** [comment]
@arthurtalkgoal 
Probably it is a precompilation issue.
Could you try `rm -rf tmp/cache` and restart rails?

FYR: The local cache should be cleared when we change handlebars' precompilation config.

**Comment by arthurtalkgoal** [comment]
I figure out I have to specific my emblem as follow as my ember-source is 1.9.0

gem 'ember-rails'
gem 'ember-source', '~> 1.9.0' # or the version you need
gem "emblem-source", github: "machty/emblem.js"
gem "barber-emblem", github: "simcha/barber-emblem"
gem "ember_devise_simple_auth"

**Comment by tricknotes** [comment]
What revision of 'barber-emblem' do you use?
I guess it will fixed by https://github.com/machty/barber-emblem/pull/1

**Comment by arthurtalkgoal** [comment]
github: "simcha/barber-emblem"

is there any problem with this?

I keep getting

```
Handlebars is not compiled error when it render the template.
```

**Comment by umeshblader3** [comment]
If you have already done rails generate ember:install, please do rails d ember:install
and it is working for me now.
