### ISSUE TITLE
Anchor regular expressions in `handlebars.rb`

### ISSUE THREAD

**Issue by carsomyr** [emberjs/ember-rails#396]
Consider adding something like `\A` to the regular expressions for template roots in [`handlebars.rb`](https://github.com/emberjs/ember-rails/blob/master/lib/ember/handlebars/template.rb#L86-L97). We ran into a problem where two roots like `["templates", "my_templates"]` would cause problems, since the logic would come by and excise `templates/` from a path like `my_templates/foo/bar`, resulting in the nonintuitive `my_foo/bar`.

**Comment by tricknotes** [comment]
Now it moves to [`ember-handlebars-template` gem](https://github.com/tricknotes/ember-handlebars-template).

@carsomyr 
If you have interest yet, please open issue to the above repository.
