### ISSUE TITLE
Invalidate cached templates when the compiler changes

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember-rails#400]
Hello!

I remember I ran into some problems with upgrading the handlebars compiler with this gem before. Since the precompiled templates need to match the handlebars runtime version, upgrading the handlebars would require invalidating the cached templates (i.e. `rm -rf tmp`). If your assets precompilation happens on the production server, you must also remember to do the same on there, otherwise your app would blow up in production after a seemingly successful deploy. (I have explained the issue in more details over [here](https://github.com/sstephenson/sprockets/issues/671).)

In Sprockets 3, [there will be a new option for plugins to influence the cache key](https://github.com/sstephenson/sprockets/pull/672) (the basis for the "hash" you see in the asset URLs) for asset files it generates. I imagine this would be quite useful in ember-rails to solve the caching problem I described.

The API is quite simple. Essentially, you just need to define a `cache_key` class method in the sprockets engine/pre-processor and the value would be added to the list of things that sprockets use to compute the asset cache key (i.e. the content of the file, its dependencies, etc).

I tried to patch this gem to see how well it works in the real world. Unfortunately, I failed to figure out how the responsibilities are split between `ember-rails`, `barber`, `ember-source` and `handlebars-source`. Nevertheless, I think it would be useful if @rwjblue, @tchak, @wycats or anyone else who's familiar with the pipeline could take a look at the [proposal](https://github.com/sstephenson/sprockets/pull/672) and see if you have anything to add.

For demonstration purpose, I built an example app that you can clone and experiment with at https://github.com/chancancode/dependable.

The issue: https://github.com/chancancode/dependable/commit/73524747713dca350dee203072e75419c943c457

Current workaround with Sprockets 2.x using `depend_on` and a dummy file: https://github.com/chancancode/dependable/compare/73524747713dca350dee203072e75419c943c457...master

Future solution with Sprockets 3+: https://github.com/chancancode/dependable/commit/5aad5fcd4f3bbec0fd623b82dcf301abf06d23f5

**Comment by evolve2k** [comment]
+1 for Handlebars 2 install tips

**Comment by tricknotes** [comment]
I regret to say it depends on sprockets 2 architecture. 
But I now supported to work with sprockets 3 on [ember-rails@0.18.0](https://github.com/tricknotes/ember-handlebars-template).

If it won't fix, please ping me.
