### ISSUE TITLE
ember-data not loading / not found

### ISSUE THREAD

**Issue by coreydemarse** [emberjs/ember-rails#422]
I made an ember/rails app about a week ago and decided to make another but now it is giving me problems, and I have no clue why.

I generated a fresh rails app, added the ember-rails gem like usual etc.
and ran the "rails generate ember:bootstrap" command

When I go to open the app in the browser, and look at the JS console it shows:
"DEBUG: Ember Data : <%= versionStamp %>"

for ember-data.

Also, in the rails console it is generating a 404 error:

Started GET "/assets/ember-data.js.map" for 127.0.0.1 at 2014-12-29 18:56:03 -0500
ActionController::RoutingError (No route matches [GET] "/assets/ember-data.js.map"):

is something amiss or am I just doing it wrong?

**Comment by tricknotes** [comment]
Thanks, @fivetanley !
The new version of ember-data is so nice :-)

**Comment by bfcoder** [comment]
So we need not worry that it is still trying to get ember-data.js.map even with the 14.1 version?

**Comment by copasetickid** [comment]
Even though this issue is closed this still occurs when you're using `ember-rails 0.16.1` and `ember-data-source 1.0.0.beta.14`.  It's currently not breaking any code would it make a difference to upgrade the gem version to get rid of the console warning?
