### ISSUE TITLE
Script tag content didn't go well with the layout in Rails

### ISSUE THREAD

**Issue by GaaraLi** [emberjs/ember-rails#430]
I got this in application layout:
```ruby
=render 'header'
=yield
=render 'footer
```
code in script tag of index.html:
```ruby
<script>
  hello world
</script>
hello
```
and the result of the view was:
```ruby
header content
hello
footer content
hello world
```
Is there something wrong with my coding or the Rails render order?

**Comment by tricknotes** [comment]
hmm, it is strange.
This behavior is against my expectation.

Could you provide a source code?
I'll see it.

**Comment by GaaraLi** [comment]
The code was almost as simple as the code above. And anything works perfect except this one.
I suggest that you can create a new project to check If I was in a bad configuration or not.

**Comment by tricknotes** [comment]
It works fine for me.

![2015-01-14 1 22 04](https://cloud.githubusercontent.com/assets/290782/5724028/f8bcd1c0-9b8b-11e4-8249-463eefa0fadc.png)
 [source code here](https://github.com/tricknotes/ember-rails-issue-430)

So I close this issue.

Probably you have something mistake or some issues other than ember-rails.
If you provide me an actual repository, I can help you :-)

**Comment by GaaraLi** [comment]
Actually, I means the render issue between ember's view and rails layout, code like:
```ruby
#index.html
<div>
<script type="text/x-handlebars" data-template-name="tags">
  content in script
</script>
content out script
</div>
```
and when I visit index action It resulted in
```ruby
header
content out script
footer
content in script
```
I checked your repo and It was just a script tag not a view of ember. 
Am I make myself clear enough?
Or I can make you a PR in you sample repo above.

**Comment by tricknotes** [comment]
I prefer a PR :-)

**Comment by GaaraLi** [comment]
BTW. I realize that the Get Start part below the repo did not mention the must command below
```ruby
rails g ember:install
```
or you can notice to make sure the ember related js were included.
Even though, the emberjs.com was the best guider site I have ever seen.

**Comment by GaaraLi** [comment]
PR ed [here](https://github.com/tricknotes/ember-rails-issue-430/pull/1)

**Comment by tricknotes** [comment]
I confirmed.
This is a natural Ember.js behavior.

Ember.js boots application as the following:

1. Parse templates and remove it from DOM tree.
2. Launch application to the bottom of `body` element.

So your example is rendered as the above.
But there are two ways to use common layout (such as header or footer).

## 1. Use `rootElement`
It allow you to launch your application in existing DOM.  [see example](https://github.com/GaaraLi/ember-rails-issue-430/pull/1)
This is recommended when you render layout by **Rails**.

## 2. Use application template
It allow you to define common layout in application template. [see example](https://github.com/GaaraLi/ember-rails-issue-430/pull/2)
This is recommended when you render layout by **Ember.js**.

**Comment by GaaraLi** [comment]
WOW, thank you very much.
Really excellent guy and solution.
