### ISSUE TITLE
Bug with pre-compilation?

### ISSUE THREAD

**Issue by clov3rly** [emberjs/ember-rails#431]
I'm getting a weird problem here. I'm totally new to ember, and rails as well, but trying to dive in.

At the moment, I'm getting `Uncaught SyntaxError: Unexpected identifier` on all my js templates. When I look at them in chrome's web inspector, these files have content like the following:

```
Ember.TEMPLATES["application"] = Ember.Handlebars.template([object Object]);
```

Which looks like some tool in the chain isn't printing out the object properly.

```
 DEBUG: -------------------------------
 DEBUG: Ember      : 1.9.1
 DEBUG: Ember Data : 1.0.0-beta.14.1
 DEBUG: Handlebars : 2.0.0
 DEBUG: jQuery     : 1.11.1
 DEBUG: -------------------------------
```

I'm using  ember-rails v 0.16.1, emblem-rails v0.2.2, emblem-source v0.3.18, coffee-rails v4.0.1 and coffee-script v2.3.0.

Not sure if this is an ember-rails bug, but I figured I'd start here.

Let me know if I can provide more info to track this down.

[Edit to add:]

```
#templates/application.js.emblem
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#" Home
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#Family" Family
        li
          a href="#Feed" Feed
        li
          a href="#Library" Library

.container      
  main
    = outlet

footer
```

**Comment by tricknotes** [comment]
You should use the head of emblem.js to precompile template with Ember.js 1.9.

``` ruby
# Gemfile
gem "emblem-source", github: "machty/emblem.js"
```

see: https://github.com/alexspeller/emblem-rails#installation
