### ISSUE TITLE
how to i18n

### ISSUE THREAD

**Issue by arthurtalkgoal** [emberjs/ember-rails#436]
Hi,

I am new to ember. I wonder how to do translation?

There is a https://github.com/jamesarosen/ember-i18n. But how to install it ? 

I tried npm install but the codes doesn't used in the ember-rails client.

**Comment by tricknotes** [comment]
It is published on [bower.io](http://bower.io).
When you install it as bower component and copy to under `vendor/assets/javascripts`, then you can use it from sprockets.
Alternatively, you can use [rails-assets](https://rails-assets.org/).

Have a nice development :-)
