### ISSUE TITLE
Can I put outlets in Rails template

### ISSUE THREAD

**Issue by arthurtalkgoal** [emberjs/ember-rails#437]
Is there any ways to render outlets in my rails erb?
(instead of defining in .js.emblem?

e.g.
```
# /rails_root/app/views/layouts/application.html.erb
<div id="sidebar">
{{outlet sidebar}}  
</div>
```

allow ember handle the sidebar content.
```
# javascripts/app/templates/application.js.emblem
= render 'menu' outlet="sidebar"
```

**Comment by tricknotes** [comment]
In this case, the following example is available.
`app/assets/javascripts/templates/application.js.hbs`
``` handlebars
<div id="sidebar">
  {{outlet sidebar}}  
</div>
```

NOTE: You can see [README](https://github.com/emberjs/ember-rails#architecture).
It will help you about basic beginning.
