### ISSUE TITLE
Uncaught Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`.

### ISSUE THREAD

**Issue by AlexCppns** [emberjs/ember-rails#439]
I am not sure why the compiler is not loaded, I am using the default settings.

**Comment by AlexCppns** [comment]
Somehow I was using Canary, fixed it.

**Comment by crux25** [comment]
I am  having the same problem. please how did you fix it?

**Comment by tricknotes** [comment]
Sorry, this is an ember-rails bug addressed at https://github.com/emberjs/ember-rails/issues/447 .
I'll fix it this night and will release a new version.

@crux25 
If you are in a hurry, you can use `ember-template-compiler.js` hosted by `http://emberjs.com`.
(such as http://builds.emberjs.com/tags/v1.10.0/ember-template-compiler.js )

**Comment by tricknotes** [comment]
see also http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html#toc_new-features-in-ember-js-1-10

**Comment by crux25** [comment]
@tricknotes 
Thanks for your response.

**Comment by tricknotes** [comment]
I released a new version [ember-rails@0.6.14](https://rubygems.org/gems/ember-rails/versions/0.16.4) with [fix for this issue](https://github.com/emberjs/ember-rails/pull/448).
This version allow you to use `//= require ember-template-compiler` in your JS.

@crux25 
If it doesn't solve yet, please ping me.

BTW: When you use handlebars precompilation (just using `app/assets/javascripts/templates/*.js.hbs`), you don't have to use `ember-template-compiler.js` and will take performance advantage.

**Comment by crux25** [comment]
I have tested the new version and it fixed the issue. 
Thanks @tricknotes

**Comment by tricknotes** [comment]
:sunglasses:

**Comment by gwert** [comment]
I'm having the same problem using ember-rails 0.6.14 and ember.js 1.10.0.  When I try using "require ember-template-compiler", I get another error: "Uncaught ReferenceError: exports is not defined".  I put the "require ember-template-compiler" statement right after handlebars and ember.  Does this need to go somewhere else?

**Comment by DrewOJensen** [comment]
@tricknotes I'm having this issue with the latest build. I am not using ember-rails at all. I'm strictly going off the embers getting started tutorial. Any ideas?
