### ISSUE TITLE
Multiple Apps

### ISSUE THREAD

**Issue by arthurtalkgoal** [emberjs/ember-rails#440]
I found that it is possible to have multiple ember apps in one rails. 
http://stackoverflow.com/questions/24456021/possible-to-have-multiple-ember-js-apps-in-one-rails-app

however, not sure how to do the config accordingly:
```

  ########################################### 
  # Ember
  ########################################### 
  
  config.ember.variant = :development
  config.handlebars.templates_root = 'app1/templates'
  config.handlebars.precompile = true
```

The config only allow one root

**Comment by bikramwp** [comment]
+1. Can someone from the ember-rails team comment on this please?

**Comment by mmun** [comment]
`config.handlebars.templates_root` accepts an array, e.g.

```
config.handlebars.templates_root = %w(app1/templates app2/templates app3/templates)
```
