### ISSUE TITLE
ember-source 1.10.0 - Barber::PrecompilerError in Ember#start

### ISSUE THREAD

**Issue by Honeycomb** [emberjs/ember-rails#441]
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using active_model_serializers 0.8.3 from git://github.com/rails-api/active_model_serializers.git (at 0-8-stable)
Using arel 6.0.0
Using activerecord 4.2.0
Using ember-source 1.10.0
Using execjs 2.3.0
Using handlebars-source 2.0.0
Using barber 0.6.0
Using bcrypt 3.1.10
Using bundler 1.7.13
Using coffee-script-source 1.9.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Using coffee-rails 4.0.1
Using ember-data-source 1.0.0.beta.14.1
Using jquery-rails 4.0.3
Using ember-rails 0.16.1
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 1.5.3
Using pg 0.18.1
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rdoc 4.2.0
Using responders 2.1.0
Using sass 3.2.19
Using sass-rails 4.0.5
Using sdoc 0.4.1
Using uglifier 2.7.0

Compiler said: Error: Closing tag `img` (on line 27) did not match last open tag `a` (on line 26).

This error arose after upgrading ember-source from 1.9.1 to 1.10.0.

**Comment by rwjblue** [comment]
As the output mentions, you that you have invalid HTML in your template. Ember 1.10.0 uses HTMLBars as its underlying templating engine, and HTMLBars validates your HTML during template compilation.
