### ISSUE TITLE
Compiler said: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by marucjmar18** [emberjs/ember-rails#442]
Why display an error:
http://steppic.com/show/cc558aca0de1374b1d12af6e0377104b.html#.VNqH2Mbf_UZ

Libs:
http://steppic.com/show/8199e08077a19e9d15fab1623eccb2e4.html#.VNqJgMbf_UY

Please Help me :)

**Comment by tricknotes** [comment]
Thanks for your report @marucjmar18 .
I fixed this issue by https://github.com/emberjs/ember-rails/pull/443.

And I released a new version [ember-rails@0.16.2](https://rubygems.org/gems/ember-rails/versions/0.16.2).
Could you try it ?

**Comment by marucjmar18** [comment]
Yes, it works :D

Thank You very much, from Poland  ;)

**Comment by tricknotes** [comment]
:stars:
