### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by IamNaN** [emberjs/ember-rails#455]
I wasn't off to a good start but things turned out in the end. Following the readme give an error on the first step. (Ruby 2.1.2 and  Rails 4.2.0.)

    ~/code% rails new example -m http://emberjs.com/edge_template.rb
    Using --skip-turbolinks --skip-test-unit --skip-bundle --database=postgresql --view-specs=false --controller-specs=false from /Users/dev/.railsrc
      create
      create  README.rdoc
    <...snip...>
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
       apply  http://emberjs.com/edge_template.rb
    /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:231:in `open_loop': HTTP redirection loop: http://emberjs.com/edge_template.rb (RuntimeError)
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:704:in `open'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open-uri.rb:34:in `open'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/actions.rb:218:in `apply'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0/lib/rails/generators/app_base.rb:143:in `apply_rails_template'
    	from (eval):1:in `apply_rails_template'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0/lib/rails/commands/application.rb:17:in `<top (required)>'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0/lib/rails/cli.rb:14:in `<top (required)>'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    	from /Users/dev/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0/bin/rails:9:in `<top (required)>'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/bin/rails:23:in `load'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/bin/rails:23:in `<main>'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/dev/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

This happened three times but then it succeeded on the fourth and subsequent attempts. Just thought I'd let someone know.

**Comment by tricknotes** [comment]
It seems a GH-pages issue. (`http://emberjs.com` is hosted on GH-pages.)
Could you retry a few more times?

ref: https://github.com/emberjs/ember-rails/issues/427

**Comment by IamNaN** [comment]
Yes, I tried it right after you replied and again several hours later. I'll close this.
