### ISSUE TITLE
ember+uglifier unbearably slow

### ISSUE THREAD

**Issue by ninja-** [emberjs/ember-rails#457]
precompiling assets in production is really, really slow when ember is included. can we do anything about it?

EDIT: after removing vendor/assets/ember the time is just 30 seconds. That's weird. But I'll stay with using ember-source gem instead.

**Comment by ninja-** [comment]
I can't believe I am the only one facing this problem...this takes about 140 seconds for me to precompile with uglifier.

**Comment by ninja-** [comment]
maybe we could wrap all the code in production folder with "eval"?

**Comment by bradleypriest** [comment]
What version of uglifier? I've found the 2.x branch to be unbearably slow, never investigated the reason, just stuck to 1.x instead
