### ISSUE TITLE
define_property.defineProperty() crashes with ember-source 1.11.0

### ISSUE THREAD

**Issue by enthrops** [emberjs/ember-rails#464]
Updating ember-source to 1.11.0 breaks my app for me.

Around line 17455 (debug version):
`define_property.defineProperty(obj, '__ember_meta__', META_DESC)`

This line throws `undefined is not a function`. If you inspect `define_property` is looks like:
`Object {hasES5CompliantDefineProperty: true, hasPropertyAccessors: true, canDefineNonEnumerableProperties: true}`.

However, if you use Ember 1.11.0 build from the official website, it does not crash, and inspecting `define_property` looks like: `Object {hasES5CompliantDefineProperty: true, defineProperty: function, hasPropertyAccessors: true, canDefineNonEnumerableProperties: true}` (it has the necessary function)

**Comment by tricknotes** [comment]
Thanks for your report @enthrops .

I think it is an ember-source issue.
So I reported this bug as https://github.com/emberjs/ember.js/issues/10770 .
