### ISSUE TITLE
Ignoring <something>/index template

### ISSUE THREAD

**Issue by noskillnoluck** [emberjs/ember-rails#473]
Good day,

I come across strange issue. To confirm that it is real I generated new rails app with
rails new my_app -m http://emberjs.com/edge_template.rb

After I created 3 templates
templates/entity.js.handlebars with content "/entity.hbs {{outlet}}"
templates/entity/index.js.handlebars with content "/entity/index.js.handlebars"
templates/entity/somehtins.js.handlebars with content "/entity/somethings.js.handlebars"

And added routes
MyApp.Router.map ()->
  @route 'entity', ->
    @route 'something'

When I visit http://localhost:3001/#/entity
I saw only templates/entity.js.handlebars and error that there are no templates/entity/index.js.handlebars
![2015-04-22 20 07 26](https://cloud.githubusercontent.com/assets/3278464/7281423/3912f044-e932-11e4-83e6-e364d8e980a2.png)

When I visit http://localhost:3001/#/entity/something
I saw that all rendered in right way
![2015-04-22 20 07 48](https://cloud.githubusercontent.com/assets/3278464/7281616/5407fd26-e933-11e4-9390-f237d63e607a.png)

In Ember.TEMPLATES entity/index is missing. It seems assets not serving right files like <...>/index.js.hbs

**Comment by tricknotes** [comment]
It seems that it related with sprockets 3.x behavior https://github.com/rails/sprockets/commit/ca76c8f9e .
But it is avoided as https://github.com/tricknotes/ember-handlebars-template/commit/b8d23970 .

If you can use latest ember-rails (and ember-handlebars-template), any other issues may be already in being.
Could you tell me what ember-rails and ember-handlebars-template versions do you use?

**Comment by noskillnoluck** [comment]
It is latest ember-rails gem (rails new my_app -m http://emberjs.com/edge_template.rb)

Gems:
rails (4.2.1)
ember-rails (0.18.2)
ember-handlebars-template (0.1.5)

Ember debug:
DEBUG: Ember      : 1.11.3
DEBUG: Ember Data : 1.0.0-beta.16.1
DEBUG: jQuery     : 1.11.2

**Comment by exop-it** [comment]
I am experiencing the same issue here (sprockets 3.0.3, ember-rails 0.18.2, ember-handlebars-template 0.1.5). 

As a workaround, you can add `gem 'sprockets', '~> 2.0'` to your Gemfile.

**Comment by tricknotes** [comment]
This is a sprockets 3.0 issue https://github.com/rails/sprockets/pull/36.
But it is already fixed on sprockets 3.1.

And now we can use it with ember-rails. (It depends on  [ember-handlebars-template@0.2.0](https://rubygems.org/gems/ember-handlebars-template/versions/0.2.0) https://github.com/emberjs/ember-rails/issues/476 )

Could you update ember-handlebars-template to 0.2.0 to solve this issue?
If not fixed yet, please ping me.

**Comment by noskillnoluck** [comment]
Thank you very much, fixed by update.
