### ISSUE TITLE
Conflict with Rails 4.2.1

### ISSUE THREAD

**Issue by JonasFromell** [emberjs/ember-rails#476]
Requirement on sprockets < 3.1, >= 2.1 conflicts with Rails 4.2.1 requirement on sprockets 3.1.0

**Comment by tricknotes** [comment]
Thanks for your report, @JonasFromell .
This should be fixed by https://github.com/tricknotes/ember-handlebars-template/pull/4 .

Could you try [ember-handlebars-template@0.2.0](https://rubygems.org/gems/ember-handlebars-template/versions/0.2.0) ?
