### ISSUE TITLE
Issue with JRuby and no handlebars

### ISSUE THREAD

**Issue by nadavshatz** [emberjs/ember-rails#477]
If you're running the Gem under JRuby without handlebars, your error will be different than the one expected at https://github.com/emberjs/ember-rails/blob/master/lib/ember_rails.rb#L11
I've forked the repo and removed the support for handlebars all together, but a real solution should still be implemented. I'll try and do it myself.

Might be worth adding jruby to the travis suite.

**Comment by tricknotes** [comment]
Oops, that's right @nadavshatz .

> Might be worth adding jruby to the travis suite.

I'm now working on it.

**Comment by nadavshatz** [comment]
Cheers! :+1:
