### ISSUE TITLE
ember.js 1.13.2 precompile error

### ISSUE THREAD

**Issue by kimsuelim** [emberjs/ember-rails#479]
Only got this problem in production mode, work fine in local.

rake aborted!
JSON::ParserError: 757: unexpected token at 'DEPRECATION: Using `{{view}}` or any path based on it (L15:C10) has been deprecated. [deprecation id: view.keyword.view] See http://emberjs.com/deprecations/v1.$#toc_view-and-controller-template-keywords for more details.

{anonymous}(/tmp/execjs20150623-32159-1kdckpyjs:11247:7)
Walker.visit (/tmp/execjs20150623-32159-1kdckpyjs:17930:7)
visitors.ElementNode (/tmp/execjs20150623-32159-1kdckpyjs:17946:16)
Walker.children (/tmp/execjs20150623-32159-1kdckpyjs:17963:7)
....

**Comment by rwjblue** [comment]
@pixelhandler - This seems like the issue you were mentioning in https://github.com/emberjs/rfcs/pull/65.

**Comment by rwjblue** [comment]
It seems like something is attempting to `JSON.parse` the output from compilation, and that parsing is blowing up on backtick characters (just a guess actually).

**Comment by rwjblue** [comment]
Might be here: https://github.com/tchak/barber/blob/fdf0f477d5f0d6be1535c8d7056562b732671f74/lib/barber/precompiler.rb#L71-L73

**Comment by ibroadfo** [comment]
this seems to occur on linuxes (at least ubuntu) but not on mac: http://stackoverflow.com/questions/31144257/rails-fails-precompile-with-ember-template-compiler

i can e.g. compile on my macbook and deploy to heroku cleanly.

**Comment by ibroadfo** [comment]
so i'm not sure if this counts as a workaround or a fix or what, but adding `therubyracer` to my gemfile appears to have nixed this issue.

presumably somewhere in the plumbing between node, execjs, barber, the json gem etc things were getting screwed up in non-euclidean ways…

**Comment by ibroadfo** [comment]
lesson learned: always blame rails!
:mountain_railway: https://github.com/rails/execjs/blob/master/lib/execjs/external_runtime.rb#L68 :railway_car:

**Comment by claubacher** [comment]
Bumping the `execjs` gem to 2.5.2 fixed this for me.

**Comment by gosukiwi** [comment]
@claubacher wow that did it! Thanks a lot! Interesting it doesn't work with the latest version though.

**Comment by locks** [comment]
I'm closing this issue as it seems that newer `execjs` does not trigger the problem. Please reopen if that's not the case, thanks!
