### ISSUE TITLE
ember-template-compiler.map 404

### ISSUE THREAD

**Issue by meleyal** [emberjs/ember-rails#487]
Using `0.19.0` I get the following error: 

``` ruby
ActionController::RoutingError (No route matches [GET] "/assets/ember-template-compiler.map")
```

I tried the following solutions to exclude or enable `.map` files:

in `config/application.rb`:

``` ruby
config.assets.precompile += [ Proc.new{ |path| !File.extname(path).in?(['.js', '.css', '.map', '.gzip', ''] ) }, /(?:\/|\\|\A)application\.(css|js)$/ ]
```

In `config/initializers/mime_types.rb`:

``` ruby
Rack::Mime::MIME_TYPES.merge!({".map" => "text/plain"})
```

As source maps are not supported by sprockets is there any way to exclude the `.map` files from the ember build?

**Comment by uconnjosh** [comment]
@meleyal were you ever able to find a solution for this?

**Comment by meleyal** [comment]
@uconnjosh a workaround I found was just creating an empty `ember-template-compiler.map.js` in `vendor/assets/javascripts` to silence the error.

**Comment by uconnjosh** [comment]
thank you :)
