### ISSUE TITLE
Cannot find component

### ISSUE THREAD

**Issue by volontarian** [emberjs/ember-rails#490]
Given this component pagination_component.js.coffee under /components

    App.PaginationComponent = Ember.Component.extend
      actions:
        goToPage: (page) ->
          alert page

and a template pagination.handlebars under /templates/components then {{pagination}} should render the template and action buttons should alert the page but instead I get this error: Uncaught Error: Assertion Failed: A helper named 'pagination' could not be found

I figured out that when I rename App.PaginationComponent to App.PaginationComponentComponent and pagination.handlebars to pagination-component.handlebars than {{pagination-component}} works.

How can I avoid renaming the component?

I'm using the following gems:

    ember-data-source 1.13.8
    ember-rails 0.19.1
    ember-source 1.13.8

**Comment by tricknotes** [comment]
>  Components must have a dash in their name

http://guides.emberjs.com/v1.13.0/components/defining-a-component/

This is an Ember's specification.
Your component may be renamed as `XPaginationComponent`, `MyPaginationComponent` or something like this.
