### ISSUE TITLE
Couldn't find file 'handlebars'

### ISSUE THREAD

**Issue by jockmac22** [emberjs/ember-rails#493]
I'm trying to use ember-source 1.13,  if I use 1.9 I don't get this problem.  Can you help with this at all?

I have read this issue: https://github.com/emberjs/ember-rails/issues/151

When I try to access my page, it says "Couldn't find file 'handlebars'", and references this line in my application.js file:

    //= require handlebars

As per that story I added:

    config.ember.variant = :development

in my config/environments/development.rb  and it has not made a difference.

Any thoughts on why this is happening?

**Comment by roblafeve** [comment]
:one:

**Comment by tricknotes** [comment]
Ember 1.13 no longer require handlebars, so you can remove `//= require handlebars` form your js.
If you want to use handlebars other than Ember template, please add `gem 'handlebars-source'` to your `Gemfile`.

If it doesn't help you, feel free to reopen this issue :-)

**Comment by roblafeve** [comment]
@tricknotes thanks!
