### ISSUE TITLE
Request: EmblemJS template support

### ISSUE THREAD

**Issue by itsjef** [emberjs/ember-rails#498]
As far as we know, Ember projects use [HandlebarsJS](handlebarsjs.com) to build templates, however, the syntax looks quite redundant and confusing sometimes. There is a framework, [EmblemJS](emblemjs.com), which has very beautiful and concise syntax, that compiles to Handlebars template. So I'm requesting you adding support for generating an Emblem template *instead/beside* of the (default) Handlebars'. Thank you very much

**Comment by tricknotes** [comment]
You ca use [emblem-rails](https://github.com/alexspeller/emblem-rails).
