### ISSUE TITLE
Generating app-name.js with dash in javascript folder

### ISSUE THREAD

**Issue by eliasjpr** [emberjs/ember-rails#512]
I was playing around with the gem and when I created an app called `personal_bookmark` it generated a `personal-bookmark.js` but application.js was requiring `#= require personal_bookmark`

**Comment by tricknotes** [comment]
Thanks for your report @eliasjpr 

This was fixed by https://github.com/emberjs/ember-rails/pull/513.
And I just publish a new version [`0.20.2`](https://rubygems.org/gems/ember-rails/versions/0.20.2) including it :rocket:

**Comment by eliasjpr** [comment]
np @tricknotes
