### ISSUE TITLE
ember-source versions

### ISSUE THREAD

**Issue by gerry3** [emberjs/ember-rails#515]
Sorry if this isn't the right place for this issue.

Ember 2.4.2 came out six days ago, but I can't update to it yet with `bundle update ember-source`.

Is there an issue or does it take a while to become available for some reason?

**Comment by tricknotes** [comment]
Thanks @gerry3 !
This is a [emberjs/ember.js](https://github.com/emberjs/ember.js)'s issue.

Now I opened a new issue as https://github.com/emberjs/ember.js/issues/13111.
So closing this :-)
