### ISSUE TITLE
Follow-up of #516 issue

### ISSUE THREAD

**Issue by yogiv88** [emberjs/ember-rails#520]
[#516 ](https://github.com/emberjs/ember-rails/issues/516) - follow up
hey thanks a lot! it is working now. 
@tricknotes but i think you have missed adding initializers directory too. 
can you provide an option so that devs can mention which directory they would want to add to ember modules, just in case devs create their own factory type.

Also, how do i add a bower_component into my ember_rails app? 

**UPDATE**
Couldn't reopen, so creating a new issue.

**Comment by tricknotes** [comment]
Thanks for mention, @yogiv88 

> can you provide an option so that devs can mention which directory they would want to add to ember modules, just in case devs create their own factory type.

That's right.
It is already landed however it is not documented yet.
So I updated readme in https://github.com/emberjs/ember-rails/commit/d43a1a11524e935e1ab92ccb832d42ec6791dfea
Please see https://github.com/emberjs/ember-rails#configuration-options .

Now you can add your own module type as the following:
``` ruby
# config/application.rb
config.ember.prefix_dirs << %w(you own module type)
```

Although having said that I think common module types should be supported by ember-rails such as `initializers` & `instance-initializers`.
So there will be landed by https://github.com/emberjs/ember-rails/pull/522

> Also, how do i add a bower_component into my ember_rails app?

Are there any use-case?
In short answer, no for now.

**Comment by yogiv88** [comment]
thanks a lot @tricknotes.

> > Also, how do i add a bower_component into my ember_rails app?

> Are there any use-case?
> In short answer, no for now.

i would want to add socket.io(socket.io-client) for my websocket connection.
it is available as a bower_component, but i am not able to add this in ember-rails.
Can you help me with this, if there is any alternate way?

**Comment by tricknotes** [comment]
There are some way for this use-case.
* Adding path to bower_component to assets path: `assets.path << 'path/to/bower_component'`
* Copy the file you want to `vendor/assets/javascript`
* Using https://rails-assets.org

You can choice the one of them.
