### ISSUE TITLE
Rails 3 support issues ember-handlebars-template and ember-es6_template

### ISSUE THREAD

**Issue by bcavileer** [emberjs/ember-rails#523]
tricknotes fixed a bug with Ember Inspector with ember-handlebars-template@0.6.0 https://github.com/emberjs/ember-inspector/issues/419 (thank you tricknotes!)

ember-handlebars-template >= 0.6.0 depends on Sprockets 3+

The last version of ember-handlebars-template to support Sprockets 2.2.1 appears to be 0.3.6.

Will ember-rails drop support Rails 3? Is this for ES6 support? (ember-es6_template) 

If this can be fixed by dropping ES6, I'd like to make a path to update ember-handlebars-template

> rails (= 3.2.22.2) was resolved to 3.2.22.2, which depends on
      railties (= 3.2.22.2) was resolved to 3.2.22.2, which depends on
        actionpack (= 3.2.22.2) was resolved to 3.2.22.2, which depends on
          sprockets (~> 2.2.1)

> ember-handlebars-template (~> 0.6.0) was resolved to 0.6.0, which depends on
      sprockets (< 3.6, >= 3.3)

**Comment by tricknotes** [comment]
> Will ember-rails drop support Rails 3? Is this for ES6 support? (ember-es6_template)

No, not yet.
As you say, you can use ember-handlebars-template 0.3.x for Sprockets 2.

We have ember-handlebars-template's [v0.3.x branch](https://github.com/tricknotes/ember-handlebars-template/tree/v0.3.x) for Sprockets 2 compatibility.
However the both support of sprockets 2 and 3 is too hard :<
So all features on master will not land to v0.3.x branch.

If you can use latest feature for ember-rails, we recommend to upgrade your rails.
