### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by confact** [emberjs/ember-rails#526]
I got error running `rails generate ember:bootstrap` in rails 5. Saying a Sprockets class doesn't exists.

I run Rails 5rc1 which runs Sprockets 4beta2.

When will ember-rails work for rails 5?

**Comment by tricknotes** [comment]
Sorry for my delay.
Now I published a new version of [ember-rails@0.21.0](https://rubygems.org/gems/ember-rails/versions/0.21.0) that support Sprockets 4.
