### ISSUE TITLE
HTMLBars templates not compiling

### ISSUE THREAD

**Issue by maschwenk** [emberjs/ember-rails#535]
Gemfile:
```
gem 'ember-rails', '0.18.5'
gem 'ember-source', '1.10.0'
gem 'ember-data-source', '1.13.0'
```
No special ember-rails config set in `application.rb`

`application.js.coffee` contains `#= require_tree ./templates`

I've cleared my asset cache many times, but still every time I load the app, I get a load of `GET` requests to template files whose content is:

`Ember.TEMPLATES["components/blablah"] = Ember.HTMLBars.template([object Object]);`

Any ideas?

**Comment by tricknotes** [comment]
Thanks for your report, @maschwenk !
This is a ember-handlebars-template's bug https://github.com/tricknotes/ember-handlebars-template/pull/30.

Now I released a new version including fix for this issue.
Can you use [ember-handlebars-template@0.7.5](https://rubygems.org/gems/ember-handlebars-template/versions/0.7.5)?

**Comment by maschwenk** [comment]
Fixed! Thank you so much for quick response!
