### ISSUE TITLE
Rails 3.2.14

### ISSUE THREAD

**Issue by pathway27** [emberjs/ember-rails#554]
Hi,

I'm trying to integrate Ember.js into an old Rails App. I'm getting errors in the console, even if I try starting from scratch via `rails new my-app -m https://emberjs.com/edge_template.rb`.

![screen shot 2018-05-15 at 4 41 43 pm](https://user-images.githubusercontent.com/1563316/40040789-ff864976-585e-11e8-8b53-2cc6c4c013f5.png)

Anything I can do?

**Comment by tricknotes** [comment]
We are sorry.
Now ember-rails doesn't support older Rails.
The latest released version (0.21.0) supports rails >= 4.2.
Ref: https://github.com/emberjs/ember-rails/blob/v0.21.0/ember-rails.gemspec#L15
